<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-01-06T16:28:15+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/London',
];
