<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-17T14:20:07+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      log_level
 * @group     bugsnag
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'log_level' => 400,
    'api_key' => 'fcab801ae8f9cd7075c6f22e5d785ce7',
    'enable_javascript_error_detection' => false,
];
