<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-12-29T10:42:03+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_tag.enabled
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Family Learning School',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => false,
                ],
            ],
            'user' => [
                'profiles_enabled' => false,
                'display_account_menu' => true,
                'gravatar' => [
                    'enabled' => true,
                    'max_level' => 'g',
                    'image_set' => 'mm',
                ],
            ],
        ],
    ],
];
